# configuration PostgreSQL
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://database:5432/gamelife?ssl=false&sslmode=disable&TimeZone=Europe/Paris
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admingamelife
spring.datasource.password=postgresqlAdmin17
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# configuration email
spring.mail.username=yassineametjar@gmail.com
spring.mail.password=iplbxvaomrkabxbl