# Configuration datasource for the development
spring.datasource.url=jdbc:${DB_TYPE}://localhost:${DB_LOCAL_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}