spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/gamelife
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admingamelife
spring.datasource.password=postgresqlAdmin17
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Disable fail_on_empty_beans
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false