version: "3.8"

services:
  database:
    container_name: database
    hostname: database
    image: postgres:16.1
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_USER_PASSWORD
      - POSTGRES_DB=$DB_DATABASE

    ports:
      - ${DB_DOCKER_PORT}:${DB_LOCAL_PORT}
    volumes:
      - type: bind
        source: ./db/gamelifev0.3.4.sql
        target: /docker-entrypoint-initdb.d/insert.sql
        read_only: true
#      - type: volume
#        source: vol_postgresql_db
#        target: /var/lib/postgresql/data


  back:
    env_file: ./.env
    depends_on:
      - database
    build:
     context: ../gamelife
    environment:
      - SPRING_APPLICATION_JSON={"spring.datasource.url":"jdbc:postgresql://database:$DB_DOCKER_PORT/$DB_DATABASE?useSSL=false&serverTimezone=Europe/Paris&allowPublicKeyRetrieval=true","spring.datasource.username":"$DB_USER","spring.datasource.password":"$DB_USER_PASSWORD"}
    restart: always
    ports:
      - 8080:8080
    links:
      - database
    volumes:
      - ../.m2:/root/.m2
    stdin_open: true
    tty: true

  front:
    build: ../../Front/gamelife
    restart: always
    ports:
      - 4200:80
    depends_on:
      - back