version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gamelife
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=totoAdmin17
    ports:
      - 3307:3306
    volumes:
      - ./Back/gamelife/db/gamelifev0.3.4.sql:/docker-entrypoint-initdb.d/0_init.sql
    networks:
      - gamelife

  back:
    depends_on:
      - mysqldb
    build: ./Back/gamelife/target
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL : jdbc:mysql://mysqldb:3306/gamelife?autoReconnect=true&useSSL=false
    networks:
      - gamelife

  front:
    build: ./Front/gamelife
    restart: always
    ports:
      - 4200:80
    networks:
      - gamelife

networks:
    gamelife: